INFO:root:GAME_MANAGER starting server
INFO:root:GAME_MANAGER initializing game
INFO:root:GAME_MANAGER initializing visualizer
INFO:root:GAME_MANAGER starting game loop
INFO:root:GAME_MANAGER wait for connections
INFO:root:SERVER serving on ('192.168.99.108', 12345)
INFO:root:SERVER connected to 192.168.99.108:58990
INFO:root:READ (192.168.99.108:58990): HELLO
INFO:root:WRITE (192.168.99.108:58990): Y: What is your name?
INFO:root:READ (192.168.99.108:58990): ben
INFO:root:SERVER connected to 192.168.99.83:53204
INFO:root:READ (192.168.99.83:53204): Hello
ERROR:root:SERVER connection provided unexpected message: Hello
INFO:root:SERVER connected to 192.168.99.83:53205
INFO:root:READ (192.168.99.83:53205): 
ERROR:root:SERVER connection provided unexpected message: 
INFO:root:SERVER connected to 192.168.99.83:53206
INFO:root:READ (192.168.99.83:53206): HELLO
INFO:root:WRITE (192.168.99.83:53206): Y: What is your name?
INFO:root:READ (192.168.99.83:53206): Aaron
INFO:root:GAME_MANAGER starting in 1 seconds
INFO:root:GAME_MANAGER play game
INFO:root:GAME_MANAGER start round 0
INFO:root:GAME_MANAGER visualizer skipped frame 1 - STARTING ben Aaron
INFO:root:WRITE (ben): Y: Rock, Paper, or Scissors?
INFO:root:WRITE (Aaron): Y: Rock, Paper, or Scissors?
INFO:root:READ (Aaron): Rock
INFO:root:READ (ben): Paper
INFO:root:GAME Paper beats Rock! Player 0 wins this round!
INFO:root:GAME_MANAGER start round 1
INFO:root:WRITE (ben): Y: Rock, Paper, or Scissors?
INFO:root:WRITE (Aaron): Y: Rock, Paper, or Scissors?
INFO:root:SERVER no message from Aaron
INFO:root:SERVER sending connection close message
INFO:root:WRITE (Aaron): N: quit
INFO:root:SERVER ping (Aaron) cancelled - connection is already closed
INFO:root:READ (ben): Rock
WARNING:root:GAME_MANAGER PlayerDisconnectedError
Traceback (most recent call last):
  File "/Users/aaron/Documents/Programming/AsyncGame/game_manager.py", line 178, in play_game
    player_outputs = await self.get_player_outputs(round)
  File "/Users/aaron/Documents/Programming/AsyncGame/game_manager.py", line 343, in get_player_outputs
    self.handle_connection_queues()
  File "/Users/aaron/Documents/Programming/AsyncGame/game_manager.py", line 158, in handle_connection_queues
    raise PlayerDisconnectedError("Player %s disconnected during game" % connection.name)
game.PlayerDisconnectedError: Player Aaron disconnected during game
INFO:root:GAME_MANAGER initializing new game
INFO:root:GAME_MANAGER wait for connections
INFO:root:GAME_MANAGER visualizer skipped frame 1 - WAITING 2 ben
INFO:root:GAME_MANAGER visualizer skipped frame 2 - WAITING 2 ben
INFO:root:GAME_MANAGER visualizer skipped frame 3 - WAITING 2 ben
INFO:root:GAME_MANAGER visualizer skipped frame 4 - WAITING 2 ben
INFO:root:GAME_MANAGER visualizer skipped frame 5 - WAITING 2 ben
INFO:root:GAME VISUALIZER: quit pygame
INFO:root:GAME_MANAGER visualizer is no longer running, exit loop
INFO:root:GAME_MANAGER check for task errors
INFO:root:GAME_MANAGER task finished successfully <Task finished name='Task-3' coro=<GameManager.visualizer_loop() done, defined at /Users/aaron/Documents/Programming/AsyncGame/game_manager.py:248> result=None>
INFO:root:GAME_MANAGER task pending <Task pending name='Task-4' coro=<GameManager.game_loop() running at /Users/aaron/Documents/Programming/AsyncGame/game_manager.py:123> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10dc298e0>()]>> - cancel
INFO:root:GAME_MANAGER task pending <Task pending name='Task-2' coro=<Server.start_server() running at /Users/aaron/Documents/Programming/AsyncGame/server.py:267> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10d88aac0>()]>> - cancel
INFO:root:GAME_MANAGER wait for pending tasks to fully shut down
WARNING:root:GAME_MANAGER ERROR game loop cancelled
Traceback (most recent call last):
  File "/Users/aaron/Documents/Programming/AsyncGame/game_manager.py", line 123, in game_loop
    self.players = await self.wait_for_connections()
  File "/Users/aaron/Documents/Programming/AsyncGame/game_manager.py", line 47, in wait_for_connections
    await asyncio.sleep(1)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 654, in sleep
    return await future
asyncio.exceptions.CancelledError
WARNING:root:SERVER ERROR server cancelled
Traceback (most recent call last):
  File "/Users/aaron/Documents/Programming/AsyncGame/server.py", line 267, in start_server
    await self.server.serve_forever()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 366, in serve_forever
    await self._serving_forever_fut
asyncio.exceptions.CancelledError
INFO:root:GAME_MANAGER pending tasks shut down successfully
INFO:root:GAME_MANAGER stop
